project_name: backplane-tools
builds:
  - env:
      - CGO_ENABLED=0
      - "GO111MODULE=on" # make sure to use go modules
      - "GOFLAGS=-mod=readonly -trimpath" # trimpath helps with producing verifiable binaries
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ldflags:
      # See also: https://pkg.go.dev/cmd/link
      - -s
      - -w
      - "-extldflags=-zrelro" # binary hardening: For further explanation look here: https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro
      - "-extldflags=-znow"

archives:
  # https://goreleaser.com/deprecations/#archivesreplacements
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'

release:
  github:
    owner: "openshift"
    name: "backplane-tools"
  prerelease: auto
